version: "2"
services:
  # graphql:
  #   container_name: graphql
  #   restart: always
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./graphql-structure/dev-database
    links:
      - mongo
